### ISSUE TITLE
problem with whois_dict.name_servers

### ISSUE THREAD

**Issue by bolandross** [nethunteros/punter#7]
> [+] Name servers found in WHOIS data:
> Traceback (most recent call last):
>   File "main.py", line 591, in <module>
>     main(target)
>   File "main.py", line 167, in main
>     for ns in whois_dict.name_servers:
> TypeError: 'NoneType' object is not iterable

I am getting this error message, any ideas?

**Comment by binkybear** [comment]
@bolandross - It's possible there is no name server and it's error'ing out looking for it.  I'll push an 'if' check statement and see if it helps.
